#include <stdio.h>
#include <stdint.h>
#include <inttypes.h>
#include <stdlib.h>
#include <string.h>
#include <strings.h>
#include <time.h>
#include <math.h>
#include <setjmp.h>
#include <dlfcn.h>
#include <vector>
#include <jpeglib.h>
#include <sys/random.h>
#include <sys/wait.h>

#include "serial.h"
#include "nmea.h"

// ==================================================================================================================

static double getTime(clockid_t ClockID=CLOCK_BOOTTIME) // read the system time at this very moment
{ struct timespec Now; clock_gettime(ClockID, &Now); return Now.tv_sec + 1e-9*Now.tv_nsec; }

// ==================================================================================================================

static int PrintHex(char *Out, const uint8_t *Byte, int Len, const char *Format="%02X")
{ int OutLen=0;
  for(int Idx=0; Idx<Len; Idx++) OutLen+=sprintf(Out+OutLen, Format, Byte[Idx]);
  return OutLen; }

// ==================================================================================================================

const char *DataFilename = "ttn-reg.dat";

static SerialPort Port;

// write given number of Data bytes to the serial port
static int SerialWrite(const uint8_t *Data, int Len)
{ int Ofs=0;
  for( ; Ofs<Len; )
  { int Write=Port.Write((const char *)(Data+Ofs), Len-Ofs);
    if(Write<0) return Write;
    if(Write==0) { usleep(1000); continue; }
    Ofs+=Write; }
  return Ofs; }

const int MaxLineLen=256;
static char InpLine[MaxLineLen];
static int InpLineLen=0;
static bool GoodLine=1;

static char *getInpLine(void)
{ char Byte=0;
  for( ; ; )
  { if(InpLineLen>=MaxLineLen) { InpLineLen=0; GoodLine=0; }
    int Read=Port.Read(&Byte, 1); if(Read<=0) return 0;
    if(Byte<' ') break;
    InpLine[InpLineLen++]=Byte; }
  if(!GoodLine) { GoodLine=1; InpLineLen=0; return 0; }
  InpLine[InpLineLen]=0;
  if(InpLineLen==0) return 0;
  InpLineLen=0; return InpLine; }

static char *WaitResp(const char *Match, double Timeout=1.0)
{ double StartTime=getTime();
  for( ; ; )
  { if(getTime()-StartTime>=Timeout) break;
    char *RxLine= getInpLine(); if(RxLine==0) { usleep(1000); continue; }
    if(strstr(RxLine, Match)) return RxLine; }
  return 0; }

// ==================================================================================================================

static char CmdLine[1024];

static const char *PortName = "/dev/ttyACM0"; // default serial port name
static       int   BaudRate = 115200;         // default baud rate on the serial port
static char        TTNCLI[512] = "ttn-lw-cli"; // installed CLI command and options

const  uint64_t JoinEUI    = UINT64_C(0x70B3D57ED0035895); // 64-bit OGN application EUI
static uint64_t DevEUI     = 0;                             // 64-bit device EUI = tracker MAC
static  char    DevID[40];                                  // device-ID created from DevEUI
static  uint8_t AppKey[16];                                 // 128-bit application key

// ==================================================================================================================
// Decode the binary payload generated by qrcode_initBytes() in the Wio-Tracker
// firmware.  The payload is: big-endian DevEUI (8 bytes), AppKey (16 bytes).

struct JPEGError
{ jpeg_error_mgr Pub;
  jmp_buf Jump; };

static void JPEGErrorExit(j_common_ptr Info)
{ JPEGError *Error=(JPEGError *)Info->err;
  (*Info->err->format_message)(Info, Error->Pub.msg_parm.s);
  longjmp(Error->Jump, 1); }

static bool LoadJPEG(const char *Filename, std::vector<uint8_t> &Pixels, int &Width, int &Height)
{ FILE *File=fopen(Filename, "rb");
  if(!File) { perror(Filename); return false; }

  jpeg_decompress_struct Info;
  JPEGError Error;
  Info.err=jpeg_std_error(&Error.Pub);
  Error.Pub.error_exit=JPEGErrorExit;
  if(setjmp(Error.Jump))
  { fprintf(stderr, "Cannot decode JPEG %s: %s\n", Filename, Error.Pub.msg_parm.s);
    jpeg_destroy_decompress(&Info); fclose(File); return false; }

  jpeg_create_decompress(&Info);
  jpeg_stdio_src(&Info, File);
  if(jpeg_read_header(&Info, TRUE)!=JPEG_HEADER_OK)
  { fprintf(stderr, "Cannot read JPEG header: %s\n", Filename);
    jpeg_destroy_decompress(&Info); fclose(File); return false; }
  Info.out_color_space=JCS_GRAYSCALE;
  jpeg_start_decompress(&Info);
  Width=(int)Info.output_width; Height=(int)Info.output_height;
  if(Width<=0 || Height<=0 || Info.output_components!=1)
  { fprintf(stderr, "Unsupported JPEG dimensions or pixel format: %s\n", Filename);
    jpeg_destroy_decompress(&Info); fclose(File); return false; }
  Pixels.resize((size_t)Width*(size_t)Height);
  while(Info.output_scanline<Info.output_height)
  { JSAMPLE *Row=Pixels.data()+(size_t)Info.output_scanline*(size_t)Width;
    JSAMPLE *Rows[1]={Row}; jpeg_read_scanlines(&Info, Rows, 1); }
  jpeg_finish_decompress(&Info);
  jpeg_destroy_decompress(&Info); fclose(File);
  return true; }

struct ZXingAPI
{ typedef void *(*ImageViewNewFn)(const uint8_t *, int, int, int, int, int);
  typedef void (*ImageViewDeleteFn)(void *);
  typedef void *(*ReaderOptionsNewFn)();
  typedef void (*ReaderOptionsDeleteFn)(void *);
  typedef void (*ReaderOptionsBoolFn)(void *, bool);
  typedef void *(*ReadBarcodesFn)(const void *, const void *);
  typedef int (*BarcodesSizeFn)(const void *);
  typedef const void *(*BarcodesAtFn)(const void *, int);
  typedef uint8_t *(*BarcodeBytesFn)(const void *, int *);
  typedef void (*BarcodesDeleteFn)(void *);
  typedef void (*FreeFn)(void *);

  void *Library;
  ImageViewNewFn ImageViewNew;
  ImageViewDeleteFn ImageViewDelete;
  ReaderOptionsNewFn ReaderOptionsNew;
  ReaderOptionsDeleteFn ReaderOptionsDelete;
  ReaderOptionsBoolFn SetTryHarder;
  ReaderOptionsBoolFn SetTryRotate;
  ReadBarcodesFn ReadBarcodes;
  BarcodesSizeFn BarcodesSize;
  BarcodesAtFn BarcodesAt;
  BarcodeBytesFn BarcodeBytes;
  BarcodesDeleteFn BarcodesDelete;
  FreeFn Free;

  ZXingAPI():Library(0),ImageViewNew(0),ImageViewDelete(0),ReaderOptionsNew(0),
    ReaderOptionsDelete(0),SetTryHarder(0),SetTryRotate(0),ReadBarcodes(0),
    BarcodesSize(0),BarcodesAt(0),BarcodeBytes(0),BarcodesDelete(0),Free(0) {}

  template <typename Type> bool Get(Type &Function, const char *Name)
  { Function=reinterpret_cast<Type>(dlsym(Library, Name)); return Function!=0; }

  bool Open()
  { const char *Names[]={"libZXing.so.3", "libZXing.so", 0};
    for(int Idx=0; Names[Idx] && !Library; Idx++) Library=dlopen(Names[Idx], RTLD_LAZY);
    if(!Library)
    { fprintf(stderr, "QR decoder libZXing was not found (install the ZXing C++ runtime)\n"); return false; }
    bool Good=true;
    Good&=Get(ImageViewNew, "ZXing_ImageView_new");
    Good&=Get(ImageViewDelete, "ZXing_ImageView_delete");
    Good&=Get(ReadBarcodes, "ZXing_ReadBarcodes");
    Good&=Get(BarcodesSize, "ZXing_Barcodes_size");
    Good&=Get(BarcodesAt, "ZXing_Barcodes_at");
    Good&=Get(BarcodeBytes, "ZXing_Barcode_bytes");
    Good&=Get(BarcodesDelete, "ZXing_Barcodes_delete");
    Good&=Get(Free, "ZXing_free");
    // These options are optional; the core decoder works without them.
    Get(ReaderOptionsNew, "ZXing_ReaderOptions_new");
    Get(ReaderOptionsDelete, "ZXing_ReaderOptions_delete");
    Get(SetTryHarder, "ZXing_ReaderOptions_setTryHarder");
    Get(SetTryRotate, "ZXing_ReaderOptions_setTryRotate");
    if(!Good)
    { fprintf(stderr, "The installed libZXing does not provide the required C API\n"); Close(); return false; }
    return true; }

  void Close()
  { if(Library) dlclose(Library); Library=0; }
};

static bool DecodeQR(const char *Filename, uint64_t &DecodedDevEUI, uint8_t DecodedAppKey[16])
{ std::vector<uint8_t> Pixels; int Width=0, Height=0;
  if(!LoadJPEG(Filename, Pixels, Width, Height)) return false;
  ZXingAPI API;
  if(!API.Open()) return false;

  // ZXing_ImageFormat_Lum from ZXingC.h; the image is one byte per pixel.
  void *Image=API.ImageViewNew(Pixels.data(), Width, Height, 0x01000000, Width, 1);
  if(!Image)
  { fprintf(stderr, "Could not create ZXing image view\n"); API.Close(); return false; }
  void *Options=API.ReaderOptionsNew ? API.ReaderOptionsNew() : 0;
  if(Options && API.SetTryHarder) API.SetTryHarder(Options, true);
  if(Options && API.SetTryRotate) API.SetTryRotate(Options, true);
  void *Barcodes=API.ReadBarcodes(Image, Options);
  bool Found=false;
  if(Barcodes)
  { int Count=API.BarcodesSize(Barcodes);
    for(int Idx=0; Idx<Count && !Found; Idx++)
    { const void *Barcode=API.BarcodesAt(Barcodes, Idx); int Length=0;
      uint8_t *Bytes=Barcode ? API.BarcodeBytes(Barcode, &Length) : 0;
      if(Bytes && Length==24)
      { DecodedDevEUI=0;
        for(int Byte=0; Byte<8; Byte++) DecodedDevEUI=(DecodedDevEUI<<8)|Bytes[Byte];
        memcpy(DecodedAppKey, Bytes+8, 16); Found=true; }
      if(Bytes) API.Free(Bytes); }
    API.BarcodesDelete(Barcodes); }
  if(Options && API.ReaderOptionsDelete) API.ReaderOptionsDelete(Options);
  API.ImageViewDelete(Image); API.Close();
  if(!Found) fprintf(stderr, "No 24-byte OGN registration QR payload found in %s\n", Filename);
  return Found; }

// ==================================================================================================================

static int HexValue(char Character)
{ if(Character>='0' && Character<='9') return Character-'0';
  if(Character>='A' && Character<='F') return Character-'A'+10;
  if(Character>='a' && Character<='f') return Character-'a'+10;
  return -1; }

static bool ParseHex(const char *Text, uint8_t *Bytes, int ByteCount, bool ExactLength)
{ if(!Text) return false;
  if(Text[0]=='0' && (Text[1]=='x' || Text[1]=='X')) Text+=2;
  size_t Length=strlen(Text), Expected=(size_t)ByteCount*2;
  if((ExactLength && Length!=Expected) || (!ExactLength && (Length==0 || Length>Expected)) || (Length&1)) return false;
  memset(Bytes, 0, ByteCount);
  int Offset=ByteCount-(int)(Length/2);
  for(size_t Idx=0; Idx<Length; Idx+=2)
  { int High=HexValue(Text[Idx]), Low=HexValue(Text[Idx+1]);
    if(High<0 || Low<0) return false;
    Bytes[Offset++]=(uint8_t)((High<<4)|Low); }
  return true; }

static bool ParseDevEUI(const char *Text, uint64_t &Value)
{ uint8_t Bytes[8]; if(!ParseHex(Text, Bytes, 8, false)) return false;
  Value=0; for(int Idx=0; Idx<8; Idx++) Value=(Value<<8)|Bytes[Idx];
  return Value!=0; }

static bool LooksLikeImage(const char *Name)
{ const char *Dot=strrchr(Name, '.');
  return Dot && (!strcasecmp(Dot, ".jpg") || !strcasecmp(Dot, ".jpeg")); }

static void PrintUsage(const char *Program)
{ printf("Usage:\n");
  printf("  %s [PORT[:BAUD]]                         query tracker and generate AppKey\n", Program);
  printf("  %s --qr IMAGE.jpg                        decode DevEUI/AppKey from QR\n", Program);
  printf("  %s --qr IMAGE.jpg --decode-only         decode and print without registering\n", Program);
  printf("  %s --dev-eui EUI --app-key KEY          register explicit credentials\n", Program);
  printf("  %s EUI KEY                               shorthand for explicit credentials\n", Program);
  printf("Options:\n");
  printf("  --port PORT[:BAUD]                       also configure a local tracker\n");
  printf("  --ttn-config FILE                       use this ttn-lw-cli config file\n");
  printf("  --help                                   show this help\n"); }

static bool SetTTNConfig(const char *Filename)
{ // The command is passed through /bin/sh by system().  Quote the path and
  // reject a single quote rather than allowing the option to alter the shell
  // command.  Normal Linux paths do not contain this character.
  if(!Filename || strchr(Filename, '\'')) return false;
  int Len=snprintf(TTNCLI, sizeof(TTNCLI), "ttn-lw-cli --config '%s'", Filename);
  return Len>0 && (size_t)Len<sizeof(TTNCLI); }

static bool QueryTrackerDevEUI(void)
{ for(int Try=0; Try<3; Try++)
  { strcpy(CmdLine, "$POGNS\r\n");
    SerialWrite((const uint8_t *)CmdLine, strlen(CmdLine));
    printf("Serial <= %s", CmdLine);
    for( ; ; )
    { char *RxLine=WaitResp("$POGNS", 1.0); if(RxLine==0) break;
      char *CPU=strstr(RxLine, "CPU=");
      if(CPU)
      { uint64_t Value=0;
        if(sscanf(CPU+4, "%" SCNx64, &Value)==1) DevEUI=Value; }
      printf("Serial => %s\n", RxLine); }
    if(DevEUI!=0) return true; }
  return false; }

static bool RegisterTTN(void)
{ sprintf(DevID, "ogntrk-%012" PRIx64, DevEUI);
  PrintHex(CmdLine, AppKey, 16);
  printf("JoinEUI=%016" PRIX64 ", DevEUI=%016" PRIX64 ", DevID=%s, AppKey=%s\n", JoinEUI, DevEUI, DevID, CmdLine);

  int CmdLen=sprintf(CmdLine, "%s end-devices delete ogn %s\n", TTNCLI, DevID);
  int CmdRet=system(CmdLine);
  printf("%s => %d\n", CmdLine, CmdRet);

  CmdLen=sprintf(CmdLine, "%s end-devices create ogn %s", TTNCLI, DevID);
  CmdLen+=sprintf(CmdLine+CmdLen, " --dev-eui %016" PRIX64 " --join-eui %016" PRIX64 " --root-keys.app-key.key ", DevEUI, JoinEUI);
  CmdLen+=PrintHex(CmdLine+CmdLen, AppKey, 16);
  CmdLen+=sprintf(CmdLine+CmdLen, " --frequency-plan-id EU_863_870_TTN --lorawan-version 1.0.3 --lorawan-phy-version 1.0.3-a");
  CmdLen+=sprintf(CmdLine+CmdLen, " --supports-join");
  CmdLen+=sprintf(CmdLine+CmdLen, " --mac-settings.status-time-periodicity 0 --mac-settings.status-count-periodicity 0");
  CmdLen+=sprintf(CmdLine+CmdLen, " --mac-settings.adr.mode.disabled");
  CmdLen+=sprintf(CmdLine+CmdLen, "\n");

  CmdRet=system(CmdLine);
  printf("%s => %d\n", CmdLine, CmdRet);
  if(CmdRet<0 || !WIFEXITED(CmdRet) || WEXITSTATUS(CmdRet)!=0) return false;
  return true; }

static bool SendAppKeyToTracker(void)
{ int CmdLen=sprintf(CmdLine, "$POGNS,AppKey=");
  CmdLen+=PrintHex(CmdLine+CmdLen, AppKey, 16);
  CmdLen+=sprintf(CmdLine+CmdLen, "\r\n");
  int Written=SerialWrite((const uint8_t *)CmdLine, CmdLen);
  if(Written!=CmdLen)
  { printf("Serial write failed: %d of %d bytes sent\n", Written, CmdLen); return false; }
  if(tcdrain(Port.DeviceHandle)<0) { perror("tcdrain"); return false; }
  printf("Serial <= %s", CmdLine);
  usleep(500000); // Give firmware time to parse and commit the parameter.
  return true; }

int main(int argc, char *argv[])
{ const char *QRFile=0, *ExplicitDevEUI=0, *ExplicitAppKey=0;
  const char *RequestedPort=0, *TTNConfig=0; bool Help=false, DecodeOnly=false;
  const char *Positional[2]={0,0}; int PositionalCount=0;
  for(int Arg=1; Arg<argc; Arg++)
  { const char *Text=argv[Arg];
    if(!strcmp(Text,"--help") || !strcmp(Text,"-h")) Help=true;
    else if(!strcmp(Text,"--decode-only")) DecodeOnly=true;
    else if((!strcmp(Text,"--qr") || !strcmp(Text,"--image")) && Arg+1<argc) QRFile=argv[++Arg];
    else if((!strcmp(Text,"--dev-eui") || !strcmp(Text,"--deveui")) && Arg+1<argc) ExplicitDevEUI=argv[++Arg];
    else if((!strcmp(Text,"--app-key") || !strcmp(Text,"--appkey")) && Arg+1<argc) ExplicitAppKey=argv[++Arg];
    else if(!strcmp(Text,"--port") && Arg+1<argc) RequestedPort=argv[++Arg];
    else if(!strcmp(Text,"--ttn-config") && Arg+1<argc) TTNConfig=argv[++Arg];
    else if(Text[0]=='-') { fprintf(stderr,"Unknown or incomplete option: %s\n",Text); return -1; }
    else if(PositionalCount<2) Positional[PositionalCount++]=Text;
    else { fprintf(stderr,"Too many positional arguments\n"); return -1; } }
  if(Help) { PrintUsage(argv[0]); return 0; }

  if(PositionalCount==1 && !QRFile && !ExplicitDevEUI && !ExplicitAppKey)
  { if(LooksLikeImage(Positional[0])) QRFile=Positional[0]; else RequestedPort=Positional[0]; }
  else if(PositionalCount==2 && !QRFile && !ExplicitDevEUI && !ExplicitAppKey)
  { ExplicitDevEUI=Positional[0]; ExplicitAppKey=Positional[1]; }
  else if(PositionalCount>0)
  { fprintf(stderr,"Positional arguments cannot be combined with the selected options\n"); PrintUsage(argv[0]); return -1; }

  if(DecodeOnly && !QRFile)
  { fprintf(stderr,"--decode-only is valid only together with --qr IMAGE.jpg\n"); return -1; }
  if(QRFile && (ExplicitDevEUI || ExplicitAppKey))
  { fprintf(stderr,"Use either --qr or explicit DevEUI/AppKey, not both\n"); return -1; }
  if((ExplicitDevEUI && !ExplicitAppKey) || (!ExplicitDevEUI && ExplicitAppKey))
  { fprintf(stderr,"Both DevEUI and AppKey are required\n"); return -1; }
  if(TTNConfig && !SetTTNConfig(TTNConfig))
  { fprintf(stderr,"Invalid or too long TTN CLI config path\n"); return -1; }

  bool HaveSerial=false;
  if(QRFile)
  { if(!DecodeQR(QRFile, DevEUI, AppKey)) return -1;
    printf("Decoded registration QR from %s\n", QRFile);
    if(DecodeOnly)
    { printf("DevEUI=%016" PRIX64 ", AppKey=", DevEUI); PrintHex(CmdLine, AppKey, 16); printf("%s\n", CmdLine); return 0; } }
  else if(ExplicitDevEUI)
  { if(!ParseDevEUI(ExplicitDevEUI, DevEUI) || !ParseHex(ExplicitAppKey, AppKey, 16, true))
    { fprintf(stderr,"Invalid DevEUI or AppKey; expected up to 16 and exactly 32 hexadecimal digits\n"); return -1; } }
  else
  { if(!RequestedPort) RequestedPort=PortName;
    char PortBuffer[128]; strncpy(PortBuffer, RequestedPort, sizeof(PortBuffer)-1); PortBuffer[sizeof(PortBuffer)-1]=0;
    char *Colon=strchr(PortBuffer,':');
    if(Colon) { *Colon=0; BaudRate=atoi(Colon+1); }
    PortName=PortBuffer;
    if(Port.Open(PortName, BaudRate)<0) { printf("Can't open %s at %dbps\n", PortName, BaudRate); return -1; }
    HaveSerial=true;
    if(!QueryTrackerDevEUI()) { fprintf(stderr,"Could not read a valid DevEUI from the tracker\n"); Port.Close(); return -1; }
    if(getrandom(AppKey, sizeof(AppKey), 0)!=(ssize_t)sizeof(AppKey))
    { printf("Could not produce AppKey\n"); Port.Close(); return -1; } }

  // An optional --port allows QR/manual registration to also configure a
  // locally connected tracker. The normal QR use case does not open it.
  if(!HaveSerial && RequestedPort)
  { char PortBuffer[128]; strncpy(PortBuffer, RequestedPort, sizeof(PortBuffer)-1); PortBuffer[sizeof(PortBuffer)-1]=0;
    char *Colon=strchr(PortBuffer,':');
    if(Colon) { *Colon=0; BaudRate=atoi(Colon+1); }
    if(Port.Open(PortBuffer, BaudRate)<0) { printf("Can't open %s at %dbps\n", PortBuffer, BaudRate); return -1; }
    HaveSerial=true; }

  if(!RegisterTTN())
  { printf("TTN registration failed%s\n", HaveSerial ? "; the AppKey was not sent to the tracker" : "");
    if(HaveSerial) Port.Close();
    return -1; }
  if(HaveSerial && !SendAppKeyToTracker()) { Port.Close(); return -1; }
  if(HaveSerial) Port.Close();
  else printf("Registration complete; no local tracker was configured\n");
  return 0; }
